### ISSUE TITLE
[Bug] Syntax errors with workflow conditional expressions, needing to reset step to 0

### ISSUE THREAD

**Issue by andyfeller** [skills/writing-javascript-actions#7]
**Describe the bug**

1. **Workflow step state is non-`0`**

   It appears that previous development on the template did not revert https://github.com/skills/writing-javascript-actions/blob/main/.github/script/STEP back to `0`

1. **Workflow conditional expressions improperly terminated**

   The conditional expressions used to selectively trigger workflows in this skills course appear to have syntax errors.  The following list of workflows use multi-line conditionals that are terminated improperly:
   
   - writing-javascript-actions/.github/workflows/4-create-javascript-files-for-action.yml
   
     ```yaml
     -41-    if: ${{ github.repository_owner != 'TBD-organization' }} 
     :42:      && needs.get_current_step.outputs.current_step == 4 }}
     ```
   
   - writing-javascript-actions/.github/workflows/5-add-action-to-workflow-file.yml
   
     ```yaml
     -44-    if: ${{ github.repository_owner != 'TBD-organization' }} 
     :45:      && needs.get_current_step.outputs.current_step == 5 }}
     ```
   - writing-javascript-actions/.github/workflows/2-configure-your-action.yml
   
     ```yaml
     -42-    if: ${{ github.repository_owner != 'TBD-organization' }} 
     :43:      && needs.get_current_step.outputs.current_step == 2 }}
     ```
   
   - writing-javascript-actions/.github/workflows/1-initialize-javascript-project.yml
   
     ```yaml
     -43-    if: ${{ github.repository_owner != 'TBD-organization' }} 
     :44:      && needs.get_current_step.outputs.current_step == 1 }}
     ```
   
   - writing-javascript-actions/.github/workflows/3-create-metadata-file.yml
   
     ```yaml
     -44-    if: ${{ github.repository_owner != 'TBD-organization' }} 
     :45:      && needs.get_current_step.outputs.current_step == 3 }}
     ```
   
   - writing-javascript-actions/.github/workflows/6-trigger-action.yml
   
     ```yaml
     -44-    if: ${{ github.repository_owner != 'TBD-organization' }} 
     :45:      && needs.get_current_step.outputs.current_step == 6 }}
     ```

1. **Invalid YAML for multi-line conditional**

   Using all of the examples above, this is invalid syntax for [block YAML use cases](https://yaml.org/spec/1.2.2/#chapter-8-block-style-productions).

   Instead of:

   ```yaml
         if: ${{ github.repository_owner != 'TBD-organization'
           && needs.get_current_step.outputs.current_step == 6 }}
   ```

   One of the following forms must be used:

   1. Single line

      ```yaml
            if: ${{ github.repository_owner != 'TBD-organization' && needs.get_current_step.outputs.current_step == 6 }}
      ```

   1. Multi line block

      ```yaml
            if: |
              ${{ github.repository_owner != 'TBD-organization'
                  && needs.get_current_step.outputs.current_step == 6 }}
      ```

**To Reproduce**
3. Click on '....'
4. Scroll down to '....'
5. See error

**Expected behavior**
Use of this skills course respected the state of the workflow step under execution without errors.

**Screenshots**

**Device information**
 - Type: [e.g. iPhone6]

**Additional context**

**Comment by andyfeller** [comment]
cc: @emilyistoofunky

**Comment by sinsukehlab** [comment]
This time, I have tried multi-line conditional expressions with `>-`.
Cf. #8
